### PR TITLE
CP-1145 Travis CI, sockjs-dart-client

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- Need CI to release

## Changes
- Setup Travis CI

## Areas of Regression
- n/a

## Testing
- CI passes

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI on Travis
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by travisreed-wf** [comment]
rosie

**Pull request merged**
