### PR TITLE
CP-1096 Release sockjs-dart-client 0.3.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1096

JIRA and PR's included in this release: 

 CP-1099  - Add close to client. Add integration tests.  - https://github.com/Workiva/sockjs-dart-client/pull/3
 CP-1104  - Add `noCredentials` config option.  - https://github.com/Workiva/sockjs-dart-client/pull/6
 CP-1145  - Travis CI, sockjs-dart-client  - https://github.com/Workiva/sockjs-dart-client/pull/8

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/sockjs-dart-client/compare/0.2.0...CP-1096_release_0.3.0

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by travisreed-wf** [comment]
rosie

**Pull request merged**
