### PR TITLE
CP-1146 Release sockjs-dart-client 0.3.1

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-1146

JIRA and PR's included in this release: 

 CP-1743  - Read remaining data from request buffer on xhr close  - https://github.com/Workiva/sockjs-dart-client/pull/10

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/sockjs-dart-client/compare/0.3.0...CP-1146_release_0.3.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/sockjs-dart-client/compare/0.3.0...0.3.1

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
