### PR TITLE
CP-1104 Add `noCredentials` config option.

### PR DESCRIPTION
**Pull request by evanweible-wf**
_Depends on #3_
## Issue
- Coverage is failing because of https://github.com/Workiva/dart_dev/issues/89 (null origin doesn't play nice with the SockJS origin unless `withCredentials` is false)
## Changes

**Source:**
- Add a config option to specify whether or not the SockJS client needs to set `withCredentials = true`

**Tests:**
- Existing tests updated to set `noCredentials` to true since they are not dealing with credentials
## Areas of Regression
- Any XHR request
## Testing
- `pub run dart_dev test --integration` passes
## Code Review

@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by travisreed-wf** [comment]
Infosec has requested a security review on this pull request

@evanweible-wf @jayudey-wf @maxwellpeterson-wf can you please coordinate that?

**Comment by rmconsole3-wf** [comment]
@evanweible-wf
* A security review has not been completed, but one is required. Please request a security review from one of the approved security reviewers listed [here](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines).

**Comment by jayudey-wf** [comment]
@michaeldavis-wf @richklein-wf @chadknight-wf could one of you provide a security review of this?

**Comment by michaeldavis-wf** [comment]
+1 security

**Pull request merged**
